%%% Version: 19 Jun 2022
%%%
%%% I  =  <MODELNAME>_indexing
%%%
%%% This function defines the indexing for the state variables 
%%% and parameter vector. As a result, specific state variables
%%% can be indexed in a human readable format, e.g., to
%%% access A, use X(I.A). Analogously, the parameter k_d can be 
%%% accessed via par(I.k_d) etc. 
%%%
%%% Input: none
%%%
%%% Output: I - indexing vector
%%%
%%%
%%% Authors: Jane Knoechel and Wilhelm Huisinga
%%%

function I = Wajima2009BloodCoagulation_indexing

%%% define state index structure 
%%%
I.nmstate = {'XII','XIIa','VIII','VIIIa','IX','IXa','XI','XIa','VII','VIIa','X',...
    'Xa','V','Va','Xa_Va','II','Xa_TFPI', 'VIIa_TF_Xa_TFPI',...
    'IIa','TAT','Fg','F','XF','FDP','D','XIII','XIIIa','Pg','P',...
    'PC','APC','Tmod','IIa_Tmod','IXa_VIIIa','TF','VII_TF','VIIa_TF','TFPI',...
    'VK','VKH2','VKO','VK_p','PS','APC_PS','Pk','K','CA','AVenom','CVenom',...
    'AT_III_Heparin','AEnox','Awarf','Cwarf','ENO_p','AUC','TaipanVenom','ATIII',...
    'delayTaipan1','delayTaipan2','AVenom_Tiger','CVenom_Tiger','AT_III_UFH'};

I.nstates  = length(I.nmstate);  % number (n) of states

for i = 1:I.nstates
    I.(I.nmstate{i}) = i;         % name to index mapping
end

%%% define parameter index structure
%%%
I.nmpar = {'v1','k1',... % name (nm) of parameters
    'v2','k2',...
    'v3','k3',...
    'v4','k4',...
    'v5','k5',...
    'v6','k6',...
    'v7','k7',...
    'v8','k8',...
    'v9','k9',...
    'v10','k10',...
    'v11','k11',...
    'v12','k12',...
    'v13','k13',...
    'v14','k14',...
    'v15','k15',...
    'v16','k16',...
    'v17','k17',...
    'v18','k18',...
    'v19','k19',...
    'v20','k20',...
    'v21','k21',...
    'v22','k22',...
    'v23','k23',...
    'v24','k24',...
    'v25','k25',...
    'c26','c27','c28','c29','c30','c31','c32',...
    'v33','k33',...
    'v34','k34',...
    'v35','k35',...
    'v36','k36',...
    'c37',...
    'v38','k38',...
    'v39','k39',...
    'v40','k40',...
    'v41','k41',...
    'v42','k42',...
    'v43','k43',...
    'R1','c44','c45','R2','c46','lmax','IC50',...
    'aII','aVII','aIX','aX','aPC','aPS','pV','pVIII','pFg',...
    'pXIII','pPg','pTmod','pXI','pTFPI','pVK','pXII','pPk',...
    'degFg','degF','degXF','degII','degIIa','degTF','degV','degVa','degVII','degVIIa','degVIII',...
    'degVIIIa','degIX','degIXa','degX','degXa','degXI','degXIa','degXII','degXIIa',...
    'degXIII','degXIIIa','degPk','degK','degPg','degP','degPC','degAPC','degPS',...
    'degFDP','degD','degTFPI','degVIIaTF','degVIITF','degAPCPS','degXaVa',...
    'degIXaVIIIa','degTmod','degIIaTmod','degXaTFPI','degVIIaTFXaTFPI',...
    'degTAT','degCA','degVK','degVK2','degVKH2','degVKO','ka_Brown','d_Brown',...
    'ka_Warf','Vd_Warf','Cl_Warf','ke_Warf','ka_Hep','Vc_Hep',...
    'Vp_Hep','Cl_Hep','Q_Hep','ke_Hep','k12_Hep','k21_Hep','VK_k12','VK_k21','VK_V',...
    'd_Taipan','ktrans_Taipan','ka_Tiger','d_Tiger','inf_rate_UFH','vtaipan','ktaipan'};

I.npar  = length(I.nmpar);        % number (n) of parameters

for i = 1:I.npar
        I.(I.nmpar{i}) = i;        % name to index mapping
end


%%% check for double naming and overlap between state and parameter names
%%%
if I.nstates ~= length(unique(I.nmstate))
    fprintf('--> There are double named state names---PLEASE FIX!\n\n');
    error(':-)');
end
if I.npar ~= length(unique(I.nmpar))
    fprintf('--> There are double named parameter names---PLEASE FIX!\n\n');
    error(':-)');
end
if ~isempty(intersect(I.nmstate,I.nmpar))
    fprintf('--> There is an overlap betwenn state and parameter names---PLEASE FIX!\n\n');
    error(':-)');
end

end

